version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      #- echo Code Scanning using SonarQube
      #- mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=cvadevops_b78am
      #- echo Connecting AWS CodeArtifact.
      #- export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain bcr --domain-owner 183610593709 --region us-east-1 --query authorizationToken --output text`
      - echo "JFROG Artifactory"

  build:
    commands:
      - echo Build started on `date`
      - pwd
      - ls -lrt 
      - ls -lrt $CODEBUILD_SRC_DIR/settings.xml
      - cp -pvr $CODEBUILD_SRC_DIR/settings.xml ~/.m2/settings.xml
      - mvn deploy
      
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/b78am.war
