version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Code Scanning using SonarQube
      - mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=cvadevops_b78am
  build:
    commands:
      - echo Build started on `date`
      - pwd
      - ls -lrta
      - ls -lrt settings.xml
      - cp -pvr settings.xml ~/.m2/settings.xml
      - mvn deploy
      
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/b78am.war