version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Changing to application directory..."
      - cd my-web-app
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt

  pre_build:
    commands:
      - cd my-web-app
      - echo "Pre-build started..."

  build:
    commands:
      - cd my-web-app
      - python -m py_compile app.py
      - echo "Build successful."

  post_build:
    commands:
      - echo "Build completed."

artifacts:
  base-directory: my-web-app
  files:
    - '**/*'