pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:17-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
    
     stage('DB') {
            steps {
                script {
                    docker.image('mysql:8.0').withRun(
                        "-e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=testdb"
                    ) { c ->

                        sleep 30  // wait for DB to be ready

                        sh """
                        docker exec ${c.id} mysql -uroot -proot -e "
                        SHOW DATABASES;
                        "
                        """
                    }
                }
            }
        }
    }
}
